ignore:
  - demos
  - docs
  - tests
  - tools
coverage:
  precision: 2
  round: down
  range: "40...100"
  status:
    project:
      default:
        threshold: 1%
        target: 100
        target: 40
    patch: yes
    changes: no
