ignore:
  - demos
  - docs
  - tests
  - tools
coverage:
  precision: 2
  round: down
  range: "40...100" # lower coverage expectations
  status:
    project:
      default:
        threshold: 1% # lower coverage diff threshold, but maybe is not working
        target: 100
        target: 40
    patch: yes
    changes: no
