<?php

namespace atk4\schema\Migration;

// NOT IMPLEMENTED !!!
class PgSQL extends \atk4\schema\Migration
{
    /** @var string Expression to create primary key */
    public $primary_key_expr = 'bigint generated by default as identity(start with 1) primary key';
}
