<?php

namespace atk4\schema\Migration;

// ONLY PARTIALLY IMPLEMENTED
class PgSQL extends \atk4\schema\Migration
{
    /** @var string Expression to create primary key */
    public $primary_key_expr = 'bigint generated by default as identity(start with 1) primary key';

    /** @var array use this array in extended classes to overwrite or extend values of default mapping */
    public $mapToPersistence = [
        'boolean'   => ['boolean'],
        'date'      =>  ['date'],
        'datetime'  =>  ['timestamp'],
        'time'      => ['time'],
    ];

    /** @var array use this array in extended classes to overwrite or extend values of default mapping */
    public $mapToAgile = [
        'boolean'   => ['boolean'],
        'date'      => ['date'],
        'datetime'  => ['datetime'],
        'time'      => ['time'],
    ];
}
